### ISSUE TITLE
[Solved] Error launching with docker-compose (`docker-credential-secretservice not installed or not available in PATH`)

### ISSUE THREAD

**Issue by iboates** [pgRouting/docker-pgrouting#11]
I was having some trouble launching with docker-compose as per the README, getting the following error:

`docker-credential-secretservice not installed or not available in PATH`

Googling led me [here](https://github.com/docker/docker-credential-helpers/issues/60#issuecomment-344846089). It is a solution for MAC OS, but it worked for me on Ubuntu 18.04.

The solution was to open `~/.docker/config.json` and removing the `credsStore` entry.

**Disclaimer:** I don't really know what this line does, I am just doing local testing so I am not worried about security here, so I advise doing more homework before doing this on a production server or other potentially dangerous environment.

**Comment by cayetanobv** [comment]
Thanks @iboates . I think this issue is related to your docker login process and not with pgrouting image. If you run ```docker logout``` and after ```docker login``` I think the credStore property is overwrited.

**Comment by ruester** [comment]
For me installing the missing tool fixed the problem:
```
sudo apt install golang-docker-credential-helpers
```

**Comment by ElderTugBoat786** [comment]
> For me installing the missing tool fixed the problem:
> 
> ```
> sudo apt install golang-docker-credential-helpers
> ```

This solution working from me!

**Comment by bhanu-redant** [comment]
> For me installing the missing tool fixed the problem:
> 
> ```
> sudo apt install golang-docker-credential-helpers
> ```

thank you

**Comment by jamilAbbas** [comment]
> For me installing the missing tool fixed the problem:
> 
> ```
> sudo apt install golang-docker-credential-helpers
> ```

A bundle of thanks. This worked for me like a charm.

**Comment by faqsarg** [comment]
thanks so much! I was really struggling with this.
