### ISSUE TITLE
Setup Github Actions

### ISSUE THREAD

**Issue by dkastl** [pgRouting/docker-pgrouting#15]
@aruneko pgRouting was granted permissions to use Github Actions, so we could now setup CI to build Docker images. https://help.github.com/en/articles/about-github-actions

**Comment by cvvergara** [comment]
alpha is here:
https://github.com/pgRouting/pgrouting/releases/tag/v3.0.0-alpha

master what in the near future is going to be beta

**Comment by cayetanobv** [comment]
Remember we have connected our DockerHub account to Github. Yesterdays PR merge (Dev to Master) built all images. You can see here all tags:
https://hub.docker.com/r/pgrouting/pgrouting/tags

**Comment by dkastl** [comment]
So merging into `master` in the pgRouting repository builds all Docker images, but merging into `develop` does not build the `dev` Docker image?

**Comment by dkastl** [comment]
Since Github Actions is indeed more something we need on pgRouting's main repository, I'm closing this issue as the remaining question is also handled in #15.
