### ISSUE TITLE
Add pgRouting 3.0.0 release versions

### ISSUE THREAD

**Issue by sanak** [pgRouting/docker-pgrouting#26]
**Is your feature request related to a problem? Please describe.**
pgRouting 3.0.0 was released at last May 20th, so it may be better to update that version.
https://lists.osgeo.org/pipermail/pgrouting-users/2020-May/002462.html

**Describe the solution you'd like**
Probably, the following images add/update will be necessary ?
- 10-2.5-3.0.0 (Add)
- 10-2.5-develop (Update)
- 10-2.5-master (Update)
- 11-2.5-3.0.0 (Add)
- 11-2.5-develop (Update)
- 11-2.5-master (Update)
- 12-3.0-3.0.0 (Add)
- 12-3.0-develop (Update)
- 12-3.0-master (Update)

**Comment by dkastl** [comment]
Good point. I think it's already built as `develop`, so we just have to update as a release.

**Comment by cayetanobv** [comment]
Updated here: https://github.com/pgRouting/docker-pgrouting/pull/27

**Comment by cayetanobv** [comment]
BTW: I didn't added Postgres 10 because I think it's not worth it. What do you think?

**Comment by dkastl** [comment]
Yes, I think it's fine to not provide each and every combination of versions.
I think Docker users often want to use the latest stuff anyway ;-)
If someone wants to have it, they can provide a PR.
