### ISSUE TITLE
Docker Hub - problem adding new versions

### ISSUE THREAD

**Issue by cayetanobv** [pgRouting/docker-pgrouting#30]
Hi @pgRouting/admins ,

I can't generate new image builds (we need to add new versions and change latest) because pgRouting Github repository does not appear here for me:

![image](https://user-images.githubusercontent.com/7315379/86122449-2a15de80-bad8-11ea-8f53-9e426b6e3af9.png)

My account is linked as Github account at Dockerhub:

![image](https://user-images.githubusercontent.com/7315379/86121511-66e0d600-bad6-11ea-910d-f7d28a3271b1.png)

**Comment by smellman** [comment]
@cayetanobv I added 12-3.0-3.0.0 and 11-3.0-3.0.0 in `BUILD RULES`.

**Comment by smellman** [comment]
Hmm, the save function doesn't work in BUILD RULES.
Also, I can't select source repository too.

**Comment by dkastl** [comment]
Same problem for me as for anyone else. Let me check the Github authentication ....

**Comment by dkastl** [comment]
In this repository there is no Docker Hub integration, but there is a Docker Hub deploy key.
Maybe I need to somehow connect Docker Hub and Github to make the repositories appear?

**Comment by dkastl** [comment]
@cayetanobv , I connected Docker Hub to Github ... I need to do this through my personal account settings, but it seems to work. Now I can select also pgRouting repostirories from the dropdown field.

It doesn't reallty feel right to grant Docker Hub all those rights (if I remember it even asks for write permission), so I will check if I can revoke them from other orgs/repos on Github.

**Comment by cayetanobv** [comment]
Great @dkastl. I just added all the new images that are now being built.
