### ISSUE TITLE
Add pgRouting 3.0.1 release version and update 3.0-develop/master

### ISSUE THREAD

**Issue by sanak** [pgRouting/docker-pgrouting#32]
**Is your feature request related to a problem? Please describe.**
pgRouting 3.0.1 was released at July 5th, and I felt that this is quite useful for debugging longer process query.
https://lists.osgeo.org/pipermail/pgrouting-dev/2020-July/002095.html

**Describe the solution you'd like**
I think that the following images add/update will be necessary.

- 11-2.5-3.0.1 (Add)
- 12-3.0-3.0.1 (Add)
- 12-3.0-develop (Update)
- 12-3.0-master (Update)

**Comment by cayetanobv** [comment]
Added PR #33  with new versions.
