### ISSUE TITLE
Add Postgres 13 to latest versions

### ISSUE THREAD

**Issue by cayetanobv** [pgRouting/docker-pgrouting#36]
**Describe the solution you'd like**
Postgres 13 was released on September 24:
https://www.postgresql.org/about/news/postgresql-13-released-2077/

We can add it to pgRouting last release (+ master and development versions).

**Comment by dkastl** [comment]
I also want to to add it to CI ... probably by the end of the week: https://github.com/pgRouting/pgrouting/issues/1612

**Comment by cayetanobv** [comment]
Solved with PR #37

**Comment by cayetanobv** [comment]
Building images now:
https://hub.docker.com/repository/docker/pgrouting/pgrouting/builds

@dkastl I will send an email to pgrouting list announcing new pg13.

**Comment by dkastl** [comment]
Thank you!
