### ISSUE TITLE
Apply for OSS project with Docker Hub?

### ISSUE THREAD

**Issue by dkastl** [pgRouting/docker-pgrouting#44]
Found this email in my mailbox:

> Hi there,
> 
> As one of the users of Docker Hub’s Autobuild service, we wanted to reach out and let you know that from June 18th, 2021 users on the free plan will no longer have access to the Autobuild feature. This means that any of your currently configured Autobuild will fail to run and you will need to upgrade to a Pro or Team account to restore functionality. You can read more about the changes on our blog.
> 
> To ease this transition we are offering 20% off Docker Pro and Team for new and returning subscriptions through June 18, 2021 so you can continue using that Autobuild goodness you know and love.
> 
> If you’re part of the Docker Open Source program, and currently leveraging Autobuilds as part of a Free plan, we want to continue supporting you and we will be reaching out to make sure you will not be impacted by this change.
> 
> Docker is wholly focused on providing you amazing and magical experiences. We really appreciate your support and the community’s understanding as the whole industry battles against these abusive crypto miners. .
> 
> Thanks,
> Team Docker

Docker Hub becomes a bit annoying, adding another limitation for non-paying users. We could apply as an OSS project, but the form questions are slighly ridiculous: https://www.docker.com/community/open-source/application

Do we want to look for an elternative? Is there one?
@cayetanobv @smellman @aruneko

**Comment by cayetanobv** [comment]
Uhmmmm, we can apply as OSS project. I don't know other free alternatives. What do you think is better for the project?

**Comment by dkastl** [comment]
Not sure about the limitations of the Github Container registry: https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry

**Comment by cayetanobv** [comment]
> Not sure about the limitations of the Github Container registry: https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry

I'm reading here about billing
https://docs.github.com/en/packages/working-with-a-github-packages-registry/migrating-to-the-container-registry-from-the-docker-registry#billing-changes
https://docs.github.com/en/billing/managing-billing-for-github-packages/about-billing-for-github-packages#about-billing-for-github-packages

**Comment by aruneko** [comment]
Shell we use Github actions to build docker images? Then we just push the images on Docker hub.

**Comment by dkastl** [comment]
I tried to look for alternatives, but I'm not sure there is a better one at the moment.
Maybe I will try to submit the tedious form ;-)

**Comment by cayetanobv** [comment]
Hi @dkastl . Did you apply as a Docker OSS project? If not I can do it. 
@aruneko regarding Github actions to build Docker images before pushing to DockerHub, do you know limitations in that sense (i.e.: max_time use per action)?

**Comment by dkastl** [comment]
@cayetanobv , thanks! And no, I didn't apply yet, because a bit too many tasks.

**Comment by cayetanobv** [comment]
I've submitted the form to apply as Docker OSS project:
![image](https://user-images.githubusercontent.com/7315379/122885278-3a554800-d33f-11eb-989f-e80cdb7f60ab.png)

**Comment by cayetanobv** [comment]
They have reopened the application form again: https://www.docker.com/community/open-source/application/?utm_campaign=2022-11-09-dsos-reapply&utm_medium=email&utm_source=marketo&mkt_tok=NzkwLVNTQi0zNzUAAAGIgjTBdrN0d_QC1ChWAaF0bSEwemVWs5IcIlHIL6Sc8Hje-lumfE2XMvE7A-O9jb0GbIdQHeBFDOJli2fTowxeJS1WhIfgT7Zo3M-NE_ujBP4

**Comment by latot** [comment]
> I've submitted the form to apply as Docker OSS project: ![image](https://user-images.githubusercontent.com/7315379/122885278-3a554800-d33f-11eb-989f-e80cdb7f60ab.png)

Still waiting for response?

**Comment by cayetanobv** [comment]
> > I've submitted the form to apply as Docker OSS project: ![image](https://user-images.githubusercontent.com/7315379/122885278-3a554800-d33f-11eb-989f-e80cdb7f60ab.png)
> 
> Still waiting for response?

Yes, I'm still wating :(

**Comment by dkastl** [comment]
I think it has been upgraded. There was this news about the free plan to run out, so I applied as Open Source project. It doesn't really look different, but the request was accepted.
