### ISSUE TITLE
Remove docker images for unsupported pgRouting versions

### ISSUE THREAD

**Issue by cvvergara** [pgRouting/docker-pgrouting#50]
Versions of pgRouting 2.x are no longer supported.
This can be cleaned by removing the docker images.

**Comment by cayetanobv** [comment]
I have added a comment related to this issue in this PR: https://github.com/pgRouting/docker-pgrouting/pull/49#discussion_r910446955

**Comment by cayetanobv** [comment]
I'm thinking about that and we could have several options:
- We can remove folders with unsupported versions.
- We can move folders with unsupported versions to a folder named `legacy_versions` or `unsupported_versions`.

What do you think?
CC: @pgRouting/admins

**Comment by sanak** [comment]
I don't know well about this repository's whole structure and policy, but similar docker-postgis (https://github.com/postgis/docker-postgis) repository seems to drop both unsupported version (PostGIS < 2.5) and older minor/patch version (PostGIS 3.0, 3.1) folders, so I think that just dropping the unsupported versions is enough.

**Comment by cvvergara** [comment]
@sanak I think we are making the policies as we move on.

@cayetanobv I like the idea of moving to legacy
Things will be there if someone wants to use it.

**Comment by cvvergara** [comment]
I would like this kind of movement done before any further changes. (before #49)

**Comment by dkastl** [comment]
In my opinion the outdated folders will always stay in the Git history for eventual historians and source code archaeologists ;-)
So I would delete them ... maybe place a note in the Readme.

**Comment by cvvergara** [comment]
Right with the commits :-)

**Comment by cvvergara** [comment]
I still think that moving or deleting should be done before other changes.

**Comment by sanak** [comment]
@cvvergara
I just want to make sure, but do you think that
1. Just deleting (or moving) pgRouting-2.x (followings folders) is enough
   - [10-2.5-2.6.1](https://github.com/pgRouting/docker-pgrouting/tree/master/10-2.5-2.6.1)
   - [10-2.5-2.6.2](https://github.com/pgRouting/docker-pgrouting/tree/master/10-2.5-2.6.2)
   - [10-2.5-2.6.3](https://github.com/pgRouting/docker-pgrouting/tree/master/10-2.5-2.6.3)
   - [11-2.5-2.6.1](https://github.com/pgRouting/docker-pgrouting/tree/master/11-2.5-2.6.1)
   - [11-2.5-2.6.2](https://github.com/pgRouting/docker-pgrouting/tree/master/11-2.5-2.6.2)
   - [11-2.5-2.6.3](https://github.com/pgRouting/docker-pgrouting/tree/master/11-2.5-2.6.3)
   - [12-3.0-2.6.3](https://github.com/pgRouting/docker-pgrouting/tree/master/12-3.0-2.6.3)
2. Or deleting (or moving) PostGIS 2.5 (No.1 folders + following folders) is also necessary
   - :
   - [10-2.5-develop](https://github.com/pgRouting/docker-pgrouting/tree/master/10-2.5-develop)
   - [10-2.5-master](https://github.com/pgRouting/docker-pgrouting/tree/master/10-2.5-master) => [10-2.5-main](https://github.com/pgRouting/docker-pgrouting/tree/update-docker-images/10-2.5-main)
   - [11-2.5-develop](https://github.com/pgRouting/docker-pgrouting/tree/master/11-2.5-develop)
   - [11-2.5-master](https://github.com/pgRouting/docker-pgrouting/tree/master/11-2.5-master) => [11-2.5-main](https://github.com/pgRouting/docker-pgrouting/tree/update-docker-images/11-2.5-main)

Note that PostGIS 2.5 docker image OS seems to be `debian:stretch` from docker-postgis [README.md](https://github.com/postgis/docker-postgis#versions--2022-06-22-).

**Comment by krashish8** [comment]
Fixed in #51

**Comment by cayetanobv** [comment]
> In my opinion the outdated folders will always stay in the Git history for eventual historians and source code archaeologists ;-) So I would delete them ... maybe place a note in the Readme.

Yes, I agree with @dkastl , we can set a note in Readme talking about our policy to deprecate versions and if somebody needs some old version it's possible to find it in the git history.
