### ISSUE TITLE
Errors in building existing docker images

### ISSUE THREAD

**Issue by krashish8** [pgRouting/docker-pgrouting#52]
E.g. for `13-3.1-3.2.0`:

```
$ docker build .
Sending build context to Docker daemon  8.192kB
Step 1/6 : FROM postgis/postgis:13-3.1
 ---> 3a40ce4c6592
Step 2/6 : LABEL maintainer="pgRouting Project - https://pgrouting.net"
 ---> Using cache
 ---> f02131a161af
Step 3/6 : ENV PGROUTING_VERSION 3.2.0
 ---> Using cache
 ---> 883f2d5437d6
Step 4/6 : ENV PGROUTING_SHA256 5cf4d2147cf0897b5e2de9f1b526339abf293226c411882dba4901ba049092ab
 ---> Using cache
 ---> 9a8e9b1517fb
Step 5/6 : RUN set -ex  && apt update  && apt install -y         libboost-atomic1.67.0         libboost-chrono1.67.0         libboost-graph1.67.0         libboost-date-time1.67.0         libboost-program-options1.67.0         libboost-system1.67.0         libboost-thread1.67.0         libcgal13  && apt install -y         build-essential         cmake         wget         libboost-graph-dev         libcgal-dev         libpq-dev         postgresql-server-dev-${PG_MAJOR}  && wget -O pgrouting.tar.gz "https://github.com/pgRouting/pgrouting/archive/v${PGROUTING_VERSION}.tar.gz"  && echo "$PGROUTING_SHA256 *pgrouting.tar.gz" | sha256sum -c -  && mkdir -p /usr/src/pgrouting  && tar         --extract         --file pgrouting.tar.gz         --directory /usr/src/pgrouting         --strip-components 1  && rm pgrouting.tar.gz  && cd /usr/src/pgrouting  && mkdir build  && cd build  && cmake ..  && make  && make install  && cd /  && rm -rf /usr/src/pgrouting  && apt-mark manual postgresql-13  && apt purge -y --autoremove         build-essential         cmake         wget         libcgal-dev         libpq-dev         libboost-graph-dev         postgresql-server-dev-${PG_MAJOR}  && rm -rf /var/lib/apt/lists/*
 ---> Running in 63a8c7a0385d
+ apt update

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

Get:1 http://deb.debian.org/debian bullseye InRelease [116 kB]
Get:2 http://security.debian.org/debian-security bullseye-security InRelease [44.1 kB]
Get:3 http://deb.debian.org/debian bullseye-updates InRelease [39.4 kB]
Get:4 http://security.debian.org/debian-security bullseye-security/main amd64 Packages [161 kB]
Get:5 http://apt.postgresql.org/pub/repos/apt bullseye-pgdg InRelease [91.7 kB]
Get:6 http://deb.debian.org/debian bullseye/main amd64 Packages [8,182 kB]
Get:7 http://apt.postgresql.org/pub/repos/apt bullseye-pgdg/main amd64 Packages [249 kB]
Get:8 http://apt.postgresql.org/pub/repos/apt bullseye-pgdg/13 amd64 Packages [2,575 B]
Get:9 http://deb.debian.org/debian bullseye-updates/main amd64 Packages [2,592 B]
Fetched 8,889 kB in 15s (583 kB/s)
Reading package lists...
Building dependency tree...
Reading state information...
53 packages can be upgraded. Run 'apt list --upgradable' to see them.
+ apt install -y libboost-atomic1.67.0 libboost-chrono1.67.0 libboost-graph1.67.0 libboost-date-time1.67.0 libboost-program-options1.67.0 libboost-system1.67.0 libboost-thread1.67.0 libcgal13

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

Reading package lists...
Building dependency tree...
Reading state information...
Package libcgal13 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Unable to locate package libboost-atomic1.67.0
E: Couldn't find any package by glob 'libboost-atomic1.67.0'
E: Unable to locate package libboost-chrono1.67.0
E: Couldn't find any package by glob 'libboost-chrono1.67.0'
E: Unable to locate package libboost-graph1.67.0
E: Couldn't find any package by glob 'libboost-graph1.67.0'
E: Unable to locate package libboost-date-time1.67.0
E: Couldn't find any package by glob 'libboost-date-time1.67.0'
E: Unable to locate package libboost-program-options1.67.0
E: Couldn't find any package by glob 'libboost-program-options1.67.0'
E: Unable to locate package libboost-system1.67.0
E: Couldn't find any package by glob 'libboost-system1.67.0'
E: Unable to locate package libboost-thread1.67.0
E: Couldn't find any package by glob 'libboost-thread1.67.0'
E: Package 'libcgal13' has no installation candidate
The command '/bin/sh -c set -ex  && apt update  && apt install -y         libboost-atomic1.67.0         libboost-chrono1.67.0         libboost-graph1.67.0         libboost-date-time1.67.0         libboost-program-options1.67.0         libboost-system1.67.0         libboost-thread1.67.0         libcgal13  && apt install -y         build-essential         cmake         wget         libboost-graph-dev         libcgal-dev         libpq-dev         postgresql-server-dev-${PG_MAJOR}  && wget -O pgrouting.tar.gz "https://github.com/pgRouting/pgrouting/archive/v${PGROUTING_VERSION}.tar.gz"  && echo "$PGROUTING_SHA256 *pgrouting.tar.gz" | sha256sum -c -  && mkdir -p /usr/src/pgrouting  && tar         --extract         --file pgrouting.tar.gz         --directory /usr/src/pgrouting         --strip-components 1  && rm pgrouting.tar.gz  && cd /usr/src/pgrouting  && mkdir build  && cd build  && cmake ..  && make  && make install  && cd /  && rm -rf /usr/src/pgrouting  && apt-mark manual postgresql-13  && apt purge -y --autoremove         build-essential         cmake         wget         libcgal-dev         libpq-dev         libboost-graph-dev         postgresql-server-dev-${PG_MAJOR}  && rm -rf /var/lib/apt/lists/*' returned a non-zero code: 100
```

@pgRouting/admins

**Comment by krashish8** [comment]
Seems that the libboost packages with version 1.67.0 are available only in debian:buster (https://packages.debian.org/search?keywords=libboost), which is not used by PostGIS (https://github.com/postgis/docker-postgis#versions--2022-06-22-): 

Packages:
1. libboost-atomic1.67.0
2. libboost-chrono1.67.0
3. libboost-graph1.67.0
4. libboost-date-time1.67.0
5. libboost-program-options1.67.0
6. libboost-system1.67.0
7. libboost-thread1.67.0

We can probably replace them with `libboost-...-dev` that uses the proper version based on debian release, or use version 1.74.0 that works for debian:buster (but this specific version might not work for other Debian releases)

It seems from the pgRouting workflow that we only need to install `libboost-graph-dev`: https://github.com/pgRouting/pgrouting/blob/1d4f0a5c7ae815ff1ed31ae90171825a764dbf72/.github/workflows/update.yml#L50

So, shall we remove these 7 packages along with libcgal13 and libcgal-dev (related #8)?

**Comment by krashish8** [comment]
There are also some certificate errors with wget:

```
+ wget -O pgrouting.tar.gz https://github.com/pgRouting/pgrouting/archive/v3.2.0.tar.gz
--2022-06-30 13:13:55--  https://github.com/pgRouting/pgrouting/archive/v3.2.0.tar.gz
Resolving github.com (github.com)... 13.234.176.102
Connecting to github.com (github.com)|13.234.176.102|:443... connected.
ERROR: The certificate of ‘github.com’ is not trusted.
ERROR: The certificate of ‘github.com’ doesn't have a known issuer.
The command '/bin/sh -c set -ex  && apt update  && apt install -y         build-essential         cmake         wget         libboost-graph-dev         libcgal-dev         libpq-dev         postgresql-server-dev-${PG_MAJOR}  && wget -O pgrouting.tar.gz "https://github.com/pgRouting/pgrouting/archive/v${PGROUTING_VERSION}.tar.gz"  && echo "$PGROUTING_SHA256 *pgrouting.tar.gz" | sha256sum -c -  && mkdir -p /usr/src/pgrouting  && tar         --extract         --file pgrouting.tar.gz         --directory /usr/src/pgrouting         --strip-components 1  && rm pgrouting.tar.gz  && cd /usr/src/pgrouting  && mkdir build  && cd build  && cmake ..  && make  && make install  && cd /  && rm -rf /usr/src/pgrouting  && apt-mark manual postgresql-13  && apt purge -y --autoremove         build-essential         cmake         wget         libcgal-dev         libpq-dev         libboost-graph-dev         postgresql-server-dev-${PG_MAJOR}  && rm -rf /var/lib/apt/lists/*' returned a non-zero code: 5
```

Probably the certificates are out of date inside the image. To fix, we can install `ca-certificates` before the wget, or just use the `--no-check-certificate` flag with wget.

Also, to prevent installing unnecessary packages, we can use `--no-install-recommends` flag along with apt install. That might reduce the image building time or the image size.

**Comment by sanak** [comment]
@krashish8  
Thanks for finding this issue.

> So, shall we remove these 7 packages along with libcgal13 and libcgal-dev (related https://github.com/pgRouting/docker-pgrouting/issues/8)?

I think that it's okay, but it's better to ask @cvvergara.
(I don't know well which debian packages are necessary for `boost/geometry` and `boost/property_map` ,etc.)

If possible, checking some tests with the built docker image will be nice.

---

> Probably the certificates are out of date inside the image. To fix, we can install `ca-certificates` before the wget, or just use the `--no-check-certificate` flag with wget.

From checking other docker settings, installing `ca-certificates` seems to be more popular.
- docker-library/redmine: https://github.com/docker-library/redmine/blob/master/5.0/Dockerfile#L10
- postgis/dokcer-postgis: https://github.com/postgis/docker-postgis/blob/master/14-master/Dockerfile#L40

---

> Also, to prevent installing unnecessary packages, we can use --no-install-recommends flag along with apt install. That might reduce the image building time or the image size.

Yes, above redmine and postgis also use the flag.

---

Probably, updating the following `update.sh` is also necessary (which I missed to check on #49...).
https://github.com/pgRouting/docker-pgrouting/blob/master/update.sh

**Comment by krashish8** [comment]
Are there any major changes that we need to do in `update.sh`?
Overall, the file looks good to me, except for changing some minor stuff like:
- master->main
- removing cdal maybe?
- anything else?

Maybe we can extract something useful from PostGIS update.sh or PostgreSQL update.sh script?
https://github.com/postgis/docker-postgis/blob/master/update.sh, https://github.com/docker-library/postgres/blob/master/update.sh

**Comment by sanak** [comment]
Oh, about `update.sh`, I missed the postgis/postgres side implementation.
> Maybe we can extract something useful from PostGIS `update.sh` or PostgreSQL `update.sh` script?
https://github.com/postgis/docker-postgis/blob/master/update.sh, https://github.com/docker-library/postgres/blob/master/update.sh

Especially, postgis side implementation seems to be a quite similar with pgrouting one, so we can reuse most of the part.

Thanks for the information!

**Comment by krashish8** [comment]
Yes, seems that pgrouting and postgis implementations are quite similar.

Just noting here - Another very minor improvement could be to update the `docker-compose` file and the template:
- https://github.com/pgRouting/docker-pgrouting/blob/master/docker-compose.yml.template#L3
- I think the service should be named as `pgrouting` instead of `postgis`, because that's the name of the docker container created, which should be pgrouting, not postgis.

**Comment by sanak** [comment]
@krashish8 I fixed this title's issue and your suggestions on PR #55, so I close this.
Thanks!
