### ISSUE TITLE
Support single docker image for a pgRouting minor release

### ISSUE THREAD

**Issue by krashish8** [pgRouting/docker-pgrouting#53]
We are having different docker images for different pgRouting patch releases.

Maybe we can have a single image `a-b-x.y` containing the latest patch release `x.y.z`, instead of several images `a-b-x.y.0`, `a-b-x.y.1`, etc because anyway, users would want to use the latest patch release.
(a = PostgreSQL version, b = PostGIS version, x.y.z = major.minor.patch version of pgRouting)

PostGIS also maintains a single docker image for a minor release: https://github.com/postgis/docker-postgis#versions--2022-06-22- and that contains the latest patch release.

@pgRouting/admins

**Comment by sanak** [comment]
I completely agree with this. Creating patch release folder will cause future combination explosion.

Note that docker-postgis team is preparing upcoming PostGIS 3.3 release,
- https://github.com/postgis/docker-postgis/pull/295
- https://github.com/postgis/docker-postgis/pull/302

so, it's better to prepare combinations with PostGIS 3.3.

**Comment by sanak** [comment]
Well, PostGIS 3.3.0 was just released today. :)
https://twitter.com/postgis/status/1563649064184721409

**Comment by krashish8** [comment]
Thanks for the info!
But it looks like they are still using PostGIS 2.5 and 3.2 in their docker container. The 3.3 is still in rc2, so we probably need to wait for some more time.

My suggestion for `pgrouting-docker` would be to have directories such as `a-b-x.y`, where `a-b` refers to the directory on PostGIS and `x.y` refers to the pgrouting minor releases that we support: currently, 3.0, 3.1, 3.2, 3.3, main, develop. We can maybe exclude the beta releases (PostgreSQL 15) and RC releases (3.3) if they are not yet updated on postgis-docker.

**Comment by sanak** [comment]
> But it looks like they are still using PostGIS 2.5 and 3.2 in their docker container. The 3.3 is still in rc2, so we probably need to wait for some more time.

Oh, I missed that.

> My suggestion for pgrouting-docker would be to have directories such as a-b-x.y, where a-b refers to the directory on PostGIS and x.y refers to the pgrouting minor releases that we support: currently, 3.0, 3.1, 3.2, 3.3, main, develop. We can maybe exclude the beta releases (PostgreSQL 15) and RC releases (3.3) if they are not yet updated on postgis-docker.

Okay, thanks for the details, and I agree with that.


TO: @pgRouting/admins (@dkastl, @cayetanobv, @cvvergara, @robe2)
Could someone of the admins approve this suggestion ?

**Comment by sanak** [comment]
@cayetanobv Could you check this structure change suggestion ?
Because I think that you are managing DockerHub pgRouting images (https://hub.docker.com/r/pgrouting/pgrouting).

**Comment by robe2** [comment]
I approve this suggestion or was I supposed to check a box somewhere?

**Comment by sanak** [comment]
@robe2 Thanks for approval.
I think that comment is enough, because this is not a Pull Request and there is no checkbox.

**Comment by cayetanobv** [comment]
Sorry for the delay in my response. I agree with this suggestion. I have little time to make these changes in the next weeks, so it would be great if somebody start working on that enhancement soon

**Comment by sanak** [comment]
@cayetanobv Thanks for approval.
Tomorrow is Japan national holiday, so I will take a look at code tomorrow.

**Comment by sanak** [comment]
@cayetanobv @krashish8 (CC: @cvvergara, @smellman)
PR #55 is ready for review, so please check it when you have a time.
Thanks,

**Comment by cayetanobv** [comment]
We can merge #55 , all is OK. Thanks for your work @sanak , well done!

**Comment by sanak** [comment]
Okay.
It's a too late, but I close this issue. 😄
