### ISSUE TITLE
Remove CGAL from v3

### ISSUE THREAD

**Issue by cayetanobv** [pgRouting/docker-pgrouting#8]
Remove CGAL from v3 image according to: https://github.com/pgRouting/pgrouting/pull/1188

**Comment by cayetanobv** [comment]
I think we can now remove CGAL from Dockerfile templates but we can not generate more pre-v3 versions. What do you think about it?

CC: @dkastl @aruneko @cvvergara @smellman @sanak

**Comment by sanak** [comment]
@cayetanobv
Well, how about to use Dockerfile `ARG` variable to support both v3 and pre-v3 versions ?  
In quite old pgRouting version (2.0), there was `-DWITH_DD` cmake flag, but in recent case,
something like `INSTALL_CGAL` flag may be good.
```diff
+ ARG INSTALL_CGAL=FALSE
:
+ && if [ "${INSTALL_CGAL}" = "TRUE" ]; then apt install -y libcgal%%CDAL_VERSION%% libcgal-dev; fi \
```
(By the way, `CDAL_VERSION` should be changed to `CGAL_VERSION` ?)

I think that `-DCMAKE_BUILD_TYPE` support may be also interesting.
(But, not sure how changing build type affect performance.)

**Comment by cayetanobv** [comment]
@sanak LGTM

**Comment by sanak** [comment]
@cayetanobv Okay, thanks for confirmation.

**Comment by sanak** [comment]
@cayetanobv (CC: @cvvergara)
Related with #50, now I think that removing CGAL is no problem.

Here is some related news.
https://github.com/pgRouting/pgrouting/issues/1345#issuecomment-1128165167

**Comment by sanak** [comment]
I removed CGAL in PR:#55 (commit:https://github.com/pgRouting/docker-pgrouting/pull/55/commits/be23190bc21ffad28de9dc0d1384fd2350a115d1), so I close this.
